Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/08/2023
Var
// Seção de Declarações das variáveis 
   r:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("digite o valor do raio da circunferencia: ")
   leia(r)
   escreva("a area da circunferencia equivale a: ",3.14159*r*r)

Fimalgoritmo